import React from 'react';
import { motion } from 'framer-motion';
import { ExternalLink, Github, Cpu, Globe, Sparkles } from 'lucide-react';

const projects = [
  {
    title: 'Gift Wizard',
    description: 'Built a data-intensive AI retrieval system using RAG, indexing scraped product data to power high-quality gift recommendations. The UI combined input-based and chatbot-driven suggestions, with responses generated by a classification model and fast in-memory indexing for cost-efficient retrieval.',
    technologies: ['Spring Boot', 'React', 'Flask', 'SBert', 'TCT-ColBERT', 'RAG'],
    icon: Sparkles,
    featured: true,
    gradient: 'from-blue-500 to-blue-600',
    bgGradient: 'from-blue-50 to-blue-100'
  },
  {
    title: 'Venue Reservation System',
    description: 'Developed a 3D venue booking platform that immerses guests in a spherical venue view, simulating the feel of being at the center of the space. Included an admin dashboard for full layout customization.',
    technologies: ['React', 'Three.js', 'Spring Boot', 'Firebase'],
    icon: Globe,
    featured: true,
    gradient: 'from-green-500 to-green-600',
    bgGradient: 'from-green-50 to-green-100'
  }
];

export default function ProjectsSection() {
  return (
    <section className="py-20 px-6">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
          className="text-center mb-16"
        >
          <h2 className="text-5xl font-light bg-gradient-to-r from-gray-800 to-gray-600 bg-clip-text text-transparent mb-6">Featured Projects</h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto">
            Innovative personal projects showcasing advanced AI integration, 
            3D visualization, and full-stack development capabilities.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 gap-8">
          {projects.map((project, index) => (
            <motion.div
              key={project.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: index * 0.2 }}
              viewport={{ once: true }}
              whileHover={{ scale: 1.02, y: -5 }}
              className="group"
            >
              <div className={`p-8 rounded-3xl bg-gradient-to-br ${project.bgGradient} shadow-ios hover:shadow-ios-large transition-all duration-300 h-full border border-white/40`}>
                {/* Project Icon & Title */}
                <div className="mb-6">
                  <div className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${project.gradient} shadow-ios flex items-center justify-center mb-4 group-hover:scale-110 transition-all duration-300`}>
                    <project.icon className="w-8 h-8 text-white" />
                  </div>
                  <h3 className="text-2xl font-semibold text-gray-800 mb-2">{project.title}</h3>
                  {project.featured && (
                    <span className="inline-block px-3 py-1 rounded-full bg-gradient-to-r from-yellow-500 to-yellow-600 text-white text-xs font-medium shadow-ios-small">
                      Featured
                    </span>
                  )}
                </div>

                {/* Description */}
                <p className="text-gray-600 leading-relaxed mb-6">
                  {project.description}
                </p>

                {/* Technologies */}
                <div className="mb-6">
                  <h4 className="text-sm font-semibold text-gray-700 mb-3 uppercase tracking-wider">
                    Technologies Used
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {project.technologies.map((tech, techIndex) => (
                      <motion.span 
                        key={techIndex}
                        initial={{ opacity: 0, scale: 0.8 }}
                        whileInView={{ opacity: 1, scale: 1 }}
                        transition={{ duration: 0.3, delay: techIndex * 0.05 }}
                        viewport={{ once: true }}
                        className="px-3 py-1 rounded-lg bg-white/60 backdrop-blur-sm shadow-ios-small text-gray-700 text-sm font-medium border border-white/30"
                      >
                        {tech}
                      </motion.span>
                    ))}
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="flex gap-4">
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    className="flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r from-gray-700 to-gray-800 shadow-ios text-white font-medium hover:shadow-ios-hover transition-all duration-200"
                  >
                    <Github className="w-4 h-4" />
                    <span>View Code</span>
                  </motion.button>
                  <motion.button
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                    className={`flex items-center gap-2 px-4 py-2 rounded-xl bg-gradient-to-r ${project.gradient} shadow-ios text-white font-medium hover:shadow-ios-hover transition-all duration-200`}
                  >
                    <ExternalLink className="w-4 h-4" />
                    <span>Live Demo</span>
                  </motion.button>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Additional Projects Teaser */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.4 }}
          viewport={{ once: true }}
          className="text-center mt-16"
        >
          <div className="p-8 rounded-3xl bg-gradient-to-br from-gray-50 to-gray-100 shadow-ios max-w-2xl mx-auto border border-white/40">
            <div className="w-12 h-12 bg-gradient-to-br from-gray-500 to-gray-600 rounded-xl shadow-ios flex items-center justify-center mx-auto mb-4">
              <Cpu className="w-6 h-6 text-white" />
            </div>
            <h3 className="text-2xl font-semibold text-gray-800 mb-4">More Projects Coming Soon</h3>
            <p className="text-gray-600 leading-relaxed">
              Always working on something new. Check back soon for more innovative projects 
              showcasing cutting-edge technologies and creative problem solving.
            </p>
          </div>
        </motion.div>
      </div>
    </section>
  );
}